---
services:
  nginx:
    image: nginx:stable-alpine@sha256:15e96e59aa3b0aada3a121296e3bce117721f42d88f5f64217ef4b18f458c6ab
    depends_on:
      - nest-app
    ports:
      - 8080:80
    configs:
      - source: nginx_default_conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - app-network
  nest-app:
    container_name: nest-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=$DATABASE_PASSWORD{}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE=${DATABASE}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
      - db-network
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - db-network

volumes:
  db-data:

configs:
  nginx_default_conf:
    file: ./nginx/default.conf

networks:
  app-network:
  db-network:
    internal: true