services:
  nginx:
    image: nginx:sha256:6c9ab46b34b89274be77bf50253f97bf8f16eb11b98128d5694a8ae9b3efa2ed
    depends_on:
      - nest-app 
    ports: 
      - 8080:80
    configs:
      - source: nginx_default_conf
        target: etc/nginx/conf.d/default.conf
    networks:
      - app-nest-network

  nest-app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: nest-app
    environment:
    - DATABASE_USER=${DATABASE_USER} 
    - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    - DATABASE=${DATABASE}
    - DATABASE_HOST=${DATABASE_HOST}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3000:3000
    networks:
      - app-nest-network
      - db-postgres-network

  postgres:
    container_name: postgres 
    image: postgres:sha256:6e9bbed548cc1ca776dd4685cfea9efe60d58df91186ec6bad7328fd03b388a5
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgres/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro 
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 20s
      timeout: 15s
      retries: 10
    ports:
      - 5432:5432
    networks:
      - db-postgres-network

volumes:
  db-data:

configs:
  nginx_default_conf:
    file: ./nginx/default.conf 

networks:
  app-nest-network:
  db-postgres-network:
    internal: true 
