services:
  nest-app:
    build: .
    container_name: nest-app
    environment:
    - DATABASE_USER=${DATABASE_USER} 
    - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    - DATABASE=${DATABASE}
    - DATABASE_HOST=${DATABASE_HOST}
  postgres:
    container_name: postgres 
    image: postgres:16
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgres/data 

volumes:
  db-data:




