name: CI Build    

on:
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@<version>

      - name: Setup node
        uses: actions/setup-node@<version>
        with: 
          node-version: <node-version>

      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        
      - name: Build Application
        run: npm run build

      - name: Upload Build
        uses: actions/upload-artifact@<version>
        with: 
          name: nextjs-build
          path: .next/